type Sound = {
    name: string,
    url: string
}

export const sounds: Sound[] = [
    { url: "sounds/amogus.mp3", name: "Amogus" },
    { url: "sounds/glorp.mp3", name: "Glorp" },
    { url: "sounds/aughhhh.mp3", name: "Aughhhh" },
    { url: "sounds/bruh.mp3", name: "Bruh" },
    { url: "sounds/CTPD.mp3", name: "CTPD" },
    { url: "sounds/discord.mp3", name: "Discord" },
    { url: "sounds/goofy.mp3", name: "Goofy" },
    { url: "sounds/haha.mp3", name: "Haha" },
    { url: "sounds/huh.mp3", name: "Huh" },
    { url: "sounds/oiia.mp3", name: "Oiia" },
    { url: "sounds/prd.mp3", name: "Prd" },
    { url: "sounds/prd2.mp3", name: "Prd 2" },
    { url: "sounds/trubka.mp3", name: "Trubka" },
    { url: "sounds/vine.mp3", name: "Vine" },
    { url: "sounds/scooby.mp3", name: "Scooby" },
    { url: "sounds/phone.mp3", name: "Phone" },
    { url: "sounds/rizz-sound-effect.mp3", name: "Rizz" },
    { url: "sounds/cr-brrr.mp3", name: "CR brrr" },
    { url: "sounds/hells-kitchen-violin.mp3", name: "Hell's Kitchen Violin" },
    { url: "sounds/jet2.mp3", name: "Jet 2 Holiday" },
    { url: "sounds/bonk.mp3", name: "Bonk" },
    { url: "sounds/deezNuts.mp3", name: "deezNuts" },
    { url: "sounds/hihihi-haw.mp3", name: "Hihihi Haw" },
    { url: "sounds/mimimimi.mp3", name: "mimimimi" },
    { url: "sounds/bomboclat.mp3", name: "bomboclat" },
    { url: "sounds/vypecky.mp3", name: "vypecky" },
    { url: "sounds/made_in_heaven.mp3", name: "made_in_heaven" },
    { url: "sounds/RickRoll.mp3", name: "RickRoll" },
    { url: "sounds/heartsteel_proc_sound.mp3", name: "Heartsteel"},
]
